FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
WORKDIR /src
COPY ["PersonalFinanceApp/PersonalFinanceApp.csproj", "PersonalFinanceApp/"]
RUN dotnet restore "PersonalFinanceApp/PersonalFinanceApp.csproj"
COPY . .
WORKDIR "/src/PersonalFinanceApp"
RUN dotnet build "PersonalFinanceApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PersonalFinanceApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PersonalFinanceApp.dll"]